name: "Tests"
on: 
  - push
  - pull_request
jobs:   
  type-checker:
    name: Type checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          args: --shepherd
          
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Install dependencies and handle caching in one go.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Unit tests
        uses: php-actions/phpunit@v3
        with:
          version: '9.5'
          php_version: '8.1'
